teams = [
    {
        "team_name": "Project API",
        "slug": "api",
        "projects": [
            {"name": "accounts-api", "url": "https://github.com/aziontech/accounts-api"},
            {"name": "api-v4-oas", "url": "https://github.com/aziontech/api-v4-oas"},
            {"name": "auth-api", "url": "https://github.com/aziontech/auth-api"},
            {"name": "azion-api-errors", "url": "https://github.com/aziontech/azion-api-errors"},
            {"name": "azion-django-extensions", "url": "https://github.com/aziontech/azion-django-extensions"},
            {"name": "azion-templates-api", "url": "https://github.com/aziontech/azion-templates-api"},
            {"name": "azion_behave_django_steps", "url": "https://github.com/aziontech/azion_behave_django_steps"},
            {"name": "azionapi-v4-go-sdk", "url": "https://github.com/aziontech/azionapi-v4-go-sdk"},
            {"name": "azionapi-v4-go-sdk-dev", "url": "https://github.com/aziontech/azionapi-v4-go-sdk-dev"},
            {"name": "azionapi-v4-openapi", "url": "https://github.com/aziontech/azionapi-v4-openapi"},
            {"name": "billing-api", "url": "https://github.com/aziontech/billing-api"},
            {"name": "cache-api-commons", "url": "https://github.com/aziontech/cache-api-commons"},
            {"name": "data-stream-api", "url": "https://github.com/aziontech/data-stream-api"},
            {"name": "dev-env-apiv4", "url": "https://github.com/aziontech/dev-env-apiv4"},
            {"name": "dns-api", "url": "https://github.com/aziontech/dns-api"},
            {"name": "dominio-api", "url": "https://github.com/aziontech/dominio-api"},
            {"name": "dummy-api", "url": "https://github.com/aziontech/dummy-api"},
            {"name": "edge-api", "url": "https://github.com/aziontech/edge-api"},
            {"name": "edge-setup-worker", "url": "https://github.com/aziontech/edge-setup-worker"},
            {"name": "edgesql-api", "url": "https://github.com/aziontech/edgesql-api"},
            {"name": "edgesql-api-worker", "url": "https://github.com/aziontech/edgesql-api-worker"},
            {"name": "freshdesk-worker", "url": "https://github.com/aziontech/freshdesk-worker"},
            {"name": "hubspot-worker", "url": "https://github.com/aziontech/hubspot-worker"},
            {"name": "identity-api", "url": "https://github.com/aziontech/identity-api"},
            {"name": "marketplace-api", "url": "https://github.com/aziontech/marketplace-api"},
            {"name": "metrics-api", "url": "https://github.com/aziontech/metrics-api"},
            {"name": "notification-center-worker", "url": "https://github.com/aziontech/notification-center-worker"},
            {"name": "orchestrator-api", "url": "https://github.com/aziontech/orchestrator-api"},
            {"name": "payments-api", "url": "https://github.com/aziontech/payments-api"},
            {"name": "policies-api", "url": "https://github.com/aziontech/policies-api"},
            {"name": "provisioning-api", "url": "https://github.com/aziontech/provisioning-api"},
            {"name": "qa-api-v4-postman", "url": "https://github.com/aziontech/qa-api-v4-postman"},
            {"name": "tls-api", "url": "https://github.com/aziontech/tls-api"},
            {"name": "users-api", "url": "https://github.com/aziontech/users-api"},
            {"name": "variables-api", "url": "https://github.com/aziontech/variables-api"},
            {"name": "vcs-api", "url": "https://github.com/aziontech/vcs-api"},
            {"name": "account-worker", "url": "https://github.com/aziontech/account-worker"}
        ],
        "members": [
            {"email": "luiz.cunha@azion.com", "github_user": "luizcunhaazion"},
            {"email": "alquimar.almeida@azion.com", "github_user": "Alquimar"},
            {"email": "antonio.neto@azion.com", "github_user": "KingofTime"},
            {"email": "lucas.generoso@azion.com", "github_user": "LucasGeneroso"},
            {"email": "rodrigo.maria@azion.com", "github_user": "rodrigomaria"},
            {"email": "talisson.galho@azion.com", "github_user": "trgalho"},
            {"email": "fabiano.gomes@azion.com", "github_user": "gomes-fdr"},
            {"email": "ronaldo.silveira@azion.com", "github_user": "ronaldofsilveira"},
            {"email": "lucas.ferreira@azion.com", "github_user": "lucas-fs"}
        ]
    },
]
