teams = [
    {
        "team_name": "Data Routing Orch",
        "slug": "dro",
        "projects": [
            {"name": "apeservice", "url": "https://github.com/aziontech/apeservice"},
            {"name": "arista_api", "url": "https://github.com/aziontech/arista_api"},
            {"name": "azion-monkeys", "url": "https://github.com/aziontech/azion-monkeys"},
            {"name": "AzionDaemon", "url": "https://github.com/aziontech/AzionDaemon"},
            {"name": "azionmanager", "url": "https://github.com/aziontech/azionmanager"},
            {"name": "azorch", "url": "https://github.com/aziontech/azorch"},
            {"name": "azorch-api", "url": "https://github.com/aziontech/azorch-api"},
            {"name": "azorch-builder", "url": "https://github.com/aziontech/azorch-builder"},
            {"name": "azorch-client", "url": "https://github.com/aziontech/azorch-client"},
            {"name": "azorch-orm", "url": "https://github.com/aziontech/azorch-orm"},
            {"name": "azorch-protobuf", "url": "https://github.com/aziontech/azorch-protobuf"},
            {"name": "azorch-tests", "url": "https://github.com/aziontech/azorch-tests"},
            {"name": "balancer", "url": "https://github.com/aziontech/balancer"},
            {"name": "balancer-storage-api", "url": "https://github.com/aziontech/balancer-storage-api"},
            {"name": "balancerstorage-protobuf", "url": "https://github.com/aziontech/balancerstorage-protobuf"},
            {"name": "certificate-manager", "url": "https://github.com/aziontech/certificate-manager"},
            {"name": "ddos_watchdog", "url": "https://github.com/aziontech/ddos_watchdog"},
            {"name": "dns-api", "url": "https://github.com/aziontech/dns-api"},
            {"name": "dnssec-utils", "url": "https://github.com/aziontech/dnssec-utils"},
            {"name": "docker-img-centos-go", "url": "https://github.com/aziontech/docker-img-centos-go"},
            {"name": "edgeservice-edgesql", "url": "https://github.com/aziontech/edgeservice-edgesql"},
            {"name": "edgeservice-env-variables", "url": "https://github.com/aziontech/edgeservice-env-variables"},
            {"name": "edgesql-api", "url": "https://github.com/aziontech/edgesql-api"},
            {"name": "edgesql-manager", "url": "https://github.com/aziontech/edgesql-manager"},
            {"name": "go-azion-auth", "url": "https://github.com/aziontech/go-azion-auth"},
            {"name": "go-azion-utils", "url": "https://github.com/aziontech/go-azion-utils"},
            {"name": "go-bird", "url": "https://github.com/aziontech/go-bird"},
            {"name": "go-sdn-utils", "url": "https://github.com/aziontech/go-sdn-utils"},
            {"name": "idns", "url": "https://github.com/aziontech/idns"},
            {"name": "idns-api", "url": "https://github.com/aziontech/idns-api"},
            {"name": "idns-api-go", "url": "https://github.com/aziontech/idns-api-go"},
            {"name": "juniper_api", "url": "https://github.com/aziontech/juniper_api"},
            {"name": "nettest", "url": "https://github.com/aziontech/nettest"},
            {"name": "orchestrator-api", "url": "https://github.com/aziontech/orchestrator-api"},
            {"name": "payments-api", "url": "https://github.com/aziontech/payments-api"},
            {"name": "provisioning-api", "url": "https://github.com/aziontech/provisioning-api"},
            {"name": "sdnrouter", "url": "https://github.com/aziontech/sdnrouter"},
            {"name": "services-api", "url": "https://github.com/aziontech/services-api"},
            {"name": "services-ui", "url": "https://github.com/aziontech/services-ui"}
        ],
        "members": [
            {"email": "helio.correa@azion.com", "github_user": "helio-neto"},
            {"email": "bruno.paixao@azion.com", "github_user": "brunomrpx"},
            {"email": "andre.silveira@azion.com", "github_user": "AndreSilveiraAzion"},
            {"email": "gregory.borin@azion.com", "github_user": "GregBorin"},
            {"email": "cleiton.marques@azion.com", "github_user": "cmarques7"},
            {"email": "adriano.krauthein@azion.com", "github_user": "askazion"}
        ]
    },

    {
        "team_name": "Project API",
        "slug": "api",
        "projects": [
            {"name": "accounts-api", "url": "https://github.com/aziontech/accounts-api"},
            {"name": "api-v4-oas", "url": "https://github.com/aziontech/api-v4-oas"},
            {"name": "auth-api", "url": "https://github.com/aziontech/auth-api"},
            {"name": "azion-api-errors", "url": "https://github.com/aziontech/azion-api-errors"},
            {"name": "azion-django-extensions", "url": "https://github.com/aziontech/azion-django-extensions"},
            {"name": "azion-templates-api", "url": "https://github.com/aziontech/azion-templates-api"},
            {"name": "azion_behave_django_steps", "url": "https://github.com/aziontech/azion_behave_django_steps"},
            {"name": "azionapi-v4-go-sdk", "url": "https://github.com/aziontech/azionapi-v4-go-sdk"},
            {"name": "azionapi-v4-go-sdk-dev", "url": "https://github.com/aziontech/azionapi-v4-go-sdk-dev"},
            {"name": "azionapi-v4-openapi", "url": "https://github.com/aziontech/azionapi-v4-openapi"},
            {"name": "billing-api", "url": "https://github.com/aziontech/billing-api"},
            {"name": "cache-api-commons", "url": "https://github.com/aziontech/cache-api-commons"},
            {"name": "data-stream-api", "url": "https://github.com/aziontech/data-stream-api"},
            {"name": "dev-env-apiv4", "url": "https://github.com/aziontech/dev-env-apiv4"},
            {"name": "dns-api", "url": "https://github.com/aziontech/dns-api"},
            {"name": "dominio-api", "url": "https://github.com/aziontech/dominio-api"},
            {"name": "dummy-api", "url": "https://github.com/aziontech/dummy-api"},
            {"name": "edge-api", "url": "https://github.com/aziontech/edge-api"},
            {"name": "edge-setup-worker", "url": "https://github.com/aziontech/edge-setup-worker"},
            {"name": "edgesql-api", "url": "https://github.com/aziontech/edgesql-api"},
            {"name": "edgesql-api-worker", "url": "https://github.com/aziontech/edgesql-api-worker"},
            {"name": "freshdesk-worker", "url": "https://github.com/aziontech/freshdesk-worker"},
            {"name": "hubspot-worker", "url": "https://github.com/aziontech/hubspot-worker"},
            {"name": "identity-api", "url": "https://github.com/aziontech/identity-api"},
            {"name": "marketplace-api", "url": "https://github.com/aziontech/marketplace-api"},
            {"name": "metrics-api", "url": "https://github.com/aziontech/metrics-api"},
            {"name": "notification-center-worker", "url": "https://github.com/aziontech/notification-center-worker"},
            {"name": "orchestrator-api", "url": "https://github.com/aziontech/orchestrator-api"},
            {"name": "payments-api", "url": "https://github.com/aziontech/payments-api"},
            {"name": "policies-api", "url": "https://github.com/aziontech/policies-api"},
            {"name": "provisioning-api", "url": "https://github.com/aziontech/provisioning-api"},
            {"name": "qa-api-v4-postman", "url": "https://github.com/aziontech/qa-api-v4-postman"},
            {"name": "tls-api", "url": "https://github.com/aziontech/tls-api"},
            {"name": "users-api", "url": "https://github.com/aziontech/users-api"},
            {"name": "variables-api", "url": "https://github.com/aziontech/variables-api"},
            {"name": "vcs-api", "url": "https://github.com/aziontech/vcs-api"},
            {"name": "account-worker", "url": "https://github.com/aziontech/account-worker"}
        ],
        "members": [
            {"email": "luiz.cunha@azion.com", "github_user": "luizcunhaazion"},
            {"email": "alquimar.almeida@azion.com", "github_user": "Alquimar"},
            {"email": "antonio.neto@azion.com", "github_user": "KingofTime"},
            {"email": "lucas.generoso@azion.com", "github_user": "LucasGeneroso"},
            {"email": "rodrigo.maria@azion.com", "github_user": "rodrigomaria"},
            {"email": "talisson.galho@azion.com", "github_user": "trgalho"},
            {"email": "fabiano.gomes@azion.com", "github_user": "gomes-fdr"},
            {"email": "ronaldo.silveira@azion.com", "github_user": "ronaldofsilveira"},
            {"email": "lucas.ferreira@azion.com", "github_user": "lucas-fs"}
        ]
    },
]
